import '../models/review_model.dart';

final List<Review> dummyReviews = [
  Review(
    id: '1',
    tripId: '1',
    userId: 'user1',
    userName: 'John Doe',
    userPhoto: 'https://randomuser.me/api/portraits/men/1.jpg',
    rating: 4.5,
    comment:
        'Hotel yang sangat nyaman dan bersih. Staff ramah dan pelayanan bagus.',
    date: DateTime.now().subtract(const Duration(days: 2)),
  ),
  Review(
    id: '2',
    tripId: '1',
    userId: 'user2',
    userName: 'Jane Smith',
    userPhoto: 'https://randomuser.me/api/portraits/women/1.jpg',
    rating: 5.0,
    comment: 'Lokasi strategis, dekat dengan pusat perbelanjaan dan restoran.',
    date: DateTime.now().subtract(const Duration(days: 5)),
  ),
  Review(
    id: '3',
    tripId: '2',
    userId: 'user3',
    userName: 'Mike Johnson',
    userPhoto: 'https://randomuser.me/api/portraits/men/2.jpg',
    rating: 4.0,
    comment: 'Sarapan enak dan bervariasi. Kamar cukup luas dan nyaman.',
    date: DateTime.now().subtract(const Duration(days: 7)),
  ),
  Review(
    id: '4',
    tripId: '2',
    userId: 'user4',
    userName: 'Sarah Wilson',
    userPhoto: 'https://randomuser.me/api/portraits/women/2.jpg',
    rating: 4.8,
    comment: 'Sangat puas dengan pelayanan. Akan kembali lagi nanti.',
    date: DateTime.now().subtract(const Duration(days: 10)),
  ),
  Review(
    id: '5',
    tripId: '3',
    userId: 'user5',
    userName: 'David Brown',
    userPhoto: 'https://randomuser.me/api/portraits/men/3.jpg',
    rating: 3.5,
    comment: 'Fasilitas hotel cukup lengkap, tapi AC di kamar kurang dingin.',
    date: DateTime.now().subtract(const Duration(days: 12)),
  ),
  Review(
    id: '6',
    tripId: '3',
    userId: 'user6',
    userName: 'Emma Davis',
    userPhoto: 'https://randomuser.me/api/portraits/women/3.jpg',
    rating: 4.2,
    comment: 'Kolam renang bagus dan bersih. Cocok untuk keluarga.',
    date: DateTime.now().subtract(const Duration(days: 15)),
  ),
  Review(
    id: '7',
    tripId: '4',
    userId: 'user7',
    userName: 'Alex Turner',
    userPhoto: 'https://randomuser.me/api/portraits/men/4.jpg',
    rating: 5.0,
    comment:
        'Pemandangan dari kamar sangat indah. Worth it untuk harga yang dibayar.',
    date: DateTime.now().subtract(const Duration(days: 18)),
  ),
  Review(
    id: '8',
    tripId: '4',
    userId: 'user8',
    userName: 'Lisa Anderson',
    userPhoto: 'https://randomuser.me/api/portraits/women/4.jpg',
    rating: 4.6,
    comment: 'WiFi cepat, parkir luas, dan keamanan 24 jam. Recommended!',
    date: DateTime.now().subtract(const Duration(days: 20)),
  ),
];
